# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c805ab16349ba72c2c4b41c6bb94a3289e87728c273000c29268ebf55bda48a6d9c74db63dc1d963604b86623200a0eb890b32e821facf42a0dfdd7a45d8792

test:
  secret_key_base: a11cae52d6a7fc49af51f9d8c1b23e6391b60850ae607a4ea0c55c5c3229f53e44e8def1af41ac9f17d566b3a6b640f0db52bff12b560283de8de405310906da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
